#!/usr/bin/env python3
##
## EPITECH PROJECT, 2021
## 209poll
## File description:
## 209poll
##

import sys
from math import *

def calcul_variance(pSize, sSize, p):
    return ((((p * (100 - p)) / 10000) / sSize) * ((pSize - sSize) / (pSize - 1)))

def calcul_confidence_95(variance):
    return (2 * (1.96 * sqrt(variance)) * 100 / 2)

def calcul_confidence_99(variance):
    return (2 * (2.58 * sqrt(variance)) * 100 / 2)

def display_calcul(nb1, nb2, nb3):
    population_size = nb1
    sample_size = nb2
    voting_intention = nb3
    variance = calcul_variance(nb1, nb2, nb3)
    interval_95_1 = nb3 - calcul_confidence_95(variance)
    interval_95_2 = nb3 + calcul_confidence_95(variance)
    interval_99_1 = nb3 - calcul_confidence_99(variance)
    interval_99_2 = nb3 + calcul_confidence_99(variance)
    interval_95 = (interval_95_1, interval_95_2)
    interval_99 = (interval_99_1, interval_99_2)
    print("Population size:\t\t%d " % population_size)
    print("Sample size:\t\t\t%d" % sample_size)
    print("Voting intentions:\t\t%0.2f%%" % voting_intention)
    print("Variance:\t\t\t%.6f" % variance)
    print("95%% confidence interval:\t[%0.2f%%; %0.2f%%]" % interval_95)
    print("99%% confidence interval:\t[%0.2f%%; %0.2f%%]" % interval_99)

if (len(sys.argv) < 2):
    print("The program needs 3 argument.")
    exit (84)

if (sys.argv[1] == "-h" and len(sys.argv) == 2):
    print("USAGE")
    print("    ./209poll pSize sSize p\n")
    print("DESCRIPTION")
    print("\tpSize\tsize of the population")
    print("\tsSize\tsize of the sample (supposed to be representative")
    print("\tp\tpercentage of voting intentions for a specific candidate")
    exit (0)

if (len(sys.argv) < 4 or len(sys.argv) > 4):
    print("The program needs 3 argument.")
    exit (84)
else:
    try:
        nb1 = int(sys.argv[1])
        if (nb1 == 0 or nb1 < 0):
            print("Value 1 should be more than 0.")
            exit (84)
        nb2 = int(sys.argv[2])
        if (nb2 == 0 or nb2 < 0):
            print("Value 2 should be more than 0.")
            exit (84)
        nb3 = float(sys.argv[3])
        if (nb3 == 0 or nb3 < 0 or nb3 >= 100):
            print("Value 3 should be more than 0.")
            exit (84)
        display_calcul(nb1, nb2, nb3)
        exit (0)
    except ValueError:
        print("Invalid parameter(s).")
        exit (84)
